export const PERMISSIONS = {
  DASHBOARD_VIEW: 'dashboard.view',
  DASHBOARD_CREATE: 'dashboard.create',
  DASHBOARD_UPDATE: 'dashboard.update',
  DASHBOARD_DELETE: 'dashboard.delete',

  USERS_VIEW: 'users.view',
  USERS_CREATE: 'users.create',
  USERS_UPDATE: 'users.update',
  USERS_DELETE: 'users.delete',
  USERS_CHANGE_PASSWORD: 'users.changePassword',
  // USERS_VIEW_LEGACY: 'users:view',
  // USERS_CREATE_LEGACY: 'users:create',
  // USERS_UPDATE_LEGACY: 'users:update',
  // USERS_DELETE_LEGACY: 'users:delete',
  // USERS_CHANGE_PASSWORD_LEGACY: 'users:changePassword',

  ROLES_VIEW: 'roles.view',
  ROLES_CREATE: 'roles.create',
  ROLES_UPDATE: 'roles.update',
  ROLES_DELETE: 'roles.delete',

  AUDIT_VIEW: 'audit.view',
  AUDIT_CREATE: 'audit.create',
  AUDIT_UPDATE: 'audit.update',
  AUDIT_DELETE: 'audit.delete',
  AUDIT_EXPORT: 'audit.export',
  AUDIT_REPORT_VIEW: 'audit.reportView',
  ACTIVITY_LOGS_VIEW: 'activitylogs.view',
  ACTIVITY_LOGS_CREATE: 'activitylogs.create',
  ACTIVITY_LOGS_UPDATE: 'activitylogs.update',
  ACTIVITY_LOGS_DELETE: 'activitylogs.delete',

  SETTINGS_VIEW: 'settings.view',
  SETTINGS_CREATE: 'settings.create',
  SETTINGS_UPDATE: 'settings.update',
  SETTINGS_DELETE: 'settings.delete',
  SYSTEM_SETTINGS_VIEW: 'systemSettings.view',
  SYSTEM_SETTINGS_CREATE: 'systemSettings.create',
  SYSTEM_SETTINGS_UPDATE: 'systemSettings.update',
  SYSTEM_SETTINGS_DELETE: 'systemSettings.delete',

  DEPARTMENTS_VIEW: 'departments.view',
  DEPARTMENTS_CREATE: 'departments.create',
  DEPARTMENTS_UPDATE: 'departments.update',
  DEPARTMENTS_DELETE: 'departments.delete',

  ORG_HIERARCHY_VIEW: 'orgHierarchy.view',
  ORG_HIERARCHY_CREATE: 'orgHierarchy.create',
  ORG_HIERARCHY_UPDATE: 'orgHierarchy.update',
  ORG_HIERARCHY_DELETE: 'orgHierarchy.delete',

  EMPLOYEE_CREATE: 'employee.create',
  EMPLOYEE_VIEW: 'employee.view',
  EMPLOYEE_UPDATE: 'employee.update',
  EMPLOYEE_DELETE: 'employee.delete',

  INVITATIONS_VIEW: 'invitations.view',
  INVITATIONS_CREATE: 'invitations.create',
  INVITATIONS_UPDATE: 'invitations.update',
  INVITATIONS_DELETE: 'invitations.delete',

  DESIGNATION_VIEW: 'designations.view',
  DESIGNATION_CREATE: 'designations.create',
  DESIGNATION_UPDATE: 'designations.update',
  DESIGNATION_DELETE: 'designations.delete',

  PROJECTS_VIEW: 'projects.view',
  PROJECTS_CREATE: 'projects.create',
  PROJECTS_UPDATE: 'projects.update',
  PROJECTS_DELETE: 'projects.delete',
  PROJECTS_ASSIGN: 'projects.assign',

  TASK_MANAGEMENT_VIEW: 'taskManagement.view',
  TASK_MANAGEMENT_CREATE: 'taskManagement.create',
  TASK_MANAGEMENT_UPDATE: 'taskManagement.update',
  TASK_MANAGEMENT_DELETE: 'taskManagement.delete',
  TASK_ASSIGNMENTS_VIEW: 'taskAssignments.view',
  TASK_ASSIGNMENTS_CREATE: 'taskAssignments.create',
  TASK_ASSIGNMENTS_UPDATE: 'taskAssignments.update',
  TASK_ASSIGNMENTS_DELETE: 'taskAssignments.delete',

  TEAMS_VIEW: 'teams.view',
  TEAMS_CREATE: 'teams.create',
  TEAMS_UPDATE: 'teams.update',
  TEAMS_DELETE: 'teams.delete',

  ATTENDANCE_VIEW: 'attendance.view',
  ATTENDANCE_VIEW_OWN: 'attendance.view_own',
  ATTENDANCE_CHECKIN: 'attendance.checkin',
  ATTENDANCE_CHECKOUT: 'attendance.checkout',
  ATTENDANCE_BREAK: 'attendance.break',
  ATTENDANCE_EDIT: 'attendance.edit',
  ATTENDANCE_EXPORT: 'attendance.export',
  ATTENDANCE_REQUEST_CORRECTION: 'attendance.request_correction',
  ATTENDANCE_APPROVE_CORRECTION: 'attendance.approve_correction',
};
